#!/usr/bin/env bash
set -e
root_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
build_dir="${root_dir}/build"
mkdir -p "${build_dir}"
book_md="${build_dir}/book.md"
truncate -s 0 "${book_md}"
files=(
  "docs/00-preface.md"
  "docs/01-grand-formula.md"
  "docs/10-ch01-why-management-backfires.md"
  "docs/11-ch02-danger-of-all-green.md"
  "docs/12-ch03-why-supervisors-last-to-know.md"
  "docs/13-ch04-why-oversight-still-blind.md"
  "docs/14-ch05-why-the-ruler-may-be-wrong.md"
  "docs/15-ch06-why-truth-becomes-irrational.md"
  "docs/16-ch07-why-independence-unmeasurable.md"
  "docs/17-ch08-why-position-determines-view.md"
  "docs/18-ch09-why-position-not-equal-vision.md"
  "docs/19-ch10-why-baseline-not-goal.md"
  "docs/20-ch11-why-good-people-lie-flat.md"
  "docs/21-ch12-why-measurement-harder-than-governance.md"
  "docs/22-ch13-why-normal-before-disaster.md"
  "docs/23-ch14-why-absolute-safety-most-dangerous.md"
  "docs/24-ch15-why-high-pressure-lie-flat-math.md"
  "docs/25-ch16-why-nuclear-cure-kills-startups.md"
  "docs/26-ch17-why-algorithm-hardens-history-bias.md"
  "docs/27-ch18-why-human-in-loop-cannot-prevent.md"
  "docs/28-ch19-why-single-track-system-fails.md"
  "docs/29-ch20-why-orthogonalists-lonely.md"
  "docs/99-epilogue-fox-and-lion.md"
  "docs/appendix-a-confluence-and-boundary.md"
  "docs/appendix-b-three-party-collusion-game.md"
  "docs/appendix-c-flip-threshold-k.md"
  "docs/appendix-d-institution-decay-law.md"
  "docs/appendix-e-ogi-math-foundation.md"
  "docs/appendix-f-parrot-to-scientist-next-gen-ai.md"
  "docs/appendix-g-math-principles-orthogonal-governance.md"
  "docs/topics-faith.md"
  "docs/topics-sheltering-problem.md"
)
for f in "${files[@]}"; do
  cat "${root_dir}/${f}" >> "${book_md}"
  echo "" >> "${book_md}"
  echo "\\newpage" >> "${book_md}"
done
echo "Built ${book_md}" >&2
